version: '3'

services:
  web:
    image: peckadesign/php:7.4-dev
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
    depends_on:
      - composer
      - statie

  statie:
    image: php:7.3-cli
    volumes:
      - ./:/app
    entrypoint: vendor/bin/statie generate source --output=html
    working_dir: /app

  composer:
    image: peckadesign/php:7.4-dev
    volumes:
      - ./:/app
    command: composer install
    working_dir: /app
